### ISSUE TITLE
Add `-v1` designation to contracts

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/protocol#24]
Given that a number of the contracts are designed to support upgrades (DAO extensions, some internal mechanisms, etc) - it might make more sense to designate all as v1 now so that future implementations are only incrementing the number versus adding the string `-v2`.

**Comment by whoabuddy** [comment]
This may be overthinking it - new extensions would start with ccd and increment a unique number, and from there it'd be simple to discern v1 to v2 and so on. With the CCIPs this will be clearly defined as well.

**Comment by radicleart** [comment]
Although we ended up with several tweaks to the proposal/voting contracts in edao which we decided to keep the extension id the same and append -v2, -v3 - this worked well for a couple of reasons; it kept the contracts together in files listings and also made it easier to track and update the client and api code.

**Comment by whoabuddy** [comment]
Closing this out, new contracts will likely use versioning as mentioned above and current structure is simple and readable.
