### ISSUE TITLE
Prepare for pox-3 stacking changes

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/protocol#57]
From Friedger in Discord:

> For stacking with friedger pool in 2.1, can you make a contract call to SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP..fast-delegation contract. The function is (delegate-stx amount-ustx) and two allow-contract-caller calls. 

We will need to create a CCIP to kick things off.

**Comment by whoabuddy** [comment]
At a high level, this would require:

- migrating the MIA/NYC mining treasuries to a new contract that supports PoX-2 stacking
- migrating the MIA/NYC mining contracts to a new version that supports the new treasury
- initiating stacking for the new MIA/NYC mining treasuries

The stacking contract and payout mechanism will remain unaffected, however the pool operator address may need to be updated as well.

One option could be to use the [Fast Pool contract](https://explorer.stacks.co/txid/0xe76bed450308e50b69507d4b7bd483c8c6b525ae0f24f137e9c359a1208bfa1c?chain=mainnet) from Friedger pool, which is [documented here in Sigle](https://app.sigle.io/friedgerpool.btc/aDpIH4Ntbvt_D74GX1HjH).

The protocol will require the ability to pause stacking through a proposal if needed, but otherwise anyone could initiate stacking for the next cycle.

**Comment by friedger** [comment]
We can simply things and just delegate to the new address as described in the section about traditional delegation

**Comment by friedger** [comment]
It is not clear to me why we need a new mining contract. Can't we just update the city info? @whoabuddy

**Comment by donieguy** [comment]
Where is the Discord server for this project? @friedger @whoabuddy

**Comment by whoabuddy** [comment]
@friedger that's a good question, the initial PR scoped out the needed changes in the treasury so that'd be the next part to look at. ccd006 doesn't use `deposit-stx` to reduce costs, which might make implementing a change like this easier after all.

@donieguy this link will redirect to an invite: https://chat.citycoins.co

**Comment by whoabuddy** [comment]
Open question: should we focus on implementing an extension that does the stacking for treasuries, and only put an option to allow contract caller in the treasuries?

This would avoid having to migrate the funds in the future, and instead the extension for stacking could be replaced and treasuries could revoke/allow.

My guess is it'd operate very similar to how FAST pool works now? @friedger

**Comment by whoabuddy** [comment]
Updated the title to reflect the new goal here: preparing for pox-3 implementation.

There are two ways we can go about this:

1. keep the current implementation as-is and replace the contract calls to `.pox` with `.pox-3` (function signatures should be the same)
2. look into an extension-based stacking contract, where:
    - each treasury would support allow/revoke only, which can designate a principal to handle stacking ops on their behalf
    - an extension would be added to delegate and lock with pox-3
    - future upgrades would require disabling and upgrading the extension, revoking the old extension from the treasury, then allowing the new one

The second option would be an ideal way to implement this but given the quick timelines the 1st may be an easier goal to achieve with this as a design spec for future stacking.

**Comment by donieguy** [comment]
I think the first option is a good short-term fix at this time that will keep things consistent for the community. The second option sounds great, but I think it's a project that will require more time.
